[package]
name = "sqm-autorate-rust"
version = "0.4.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
codegen-units = 1
lto = true
opt-level = 's'

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = "abort"
strip = "symbols"


[dependencies]
anyhow = "1.0"
icmp-socket2 = "0.6.0"
fastrand = "2"
rustix = { version = "1.1", features = ["fs", "system", "thread", "time"] }
thiserror = "2.0"
libc = "0.2"
flume = { version = "0.12.0",  default-features = false, features = ["eventual-fairness", "select"] }
config = { version = "0.15.25", default-features = false }
csv = "1.4.0"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", optional = true }
uci-derive = { path = "crates/uci-derive" }

[dependencies.log]
features = ["std"]
version = "0.4"

[target.'cfg(target_os = "linux")'.dependencies]
netlink-bindings = { version = "0.3.3", features = ["rt-link", "tc"] }
netlink-socket2 = { version = "0.3.3" }

[target.'cfg(unix)'.dependencies]
rust-uci = { git = "https://github.com/Lochnair/rust-uci.git", rev = "fcfedd204fb76928ef617bf9631b041c816e03d4", optional = true, default-features = false, }

[features]
default = ["toml", "uci-vendored"]
toml = ["config/toml"]
uci = ["dep:rust-uci"]
uci-vendored = ["uci", "rust-uci/vendored"]
trace = ["dep:serde_json"]

[workspace]
members = ["crates/uci-derive"]
resolver = "3"
