[target.x86_64-unknown-freebsd]
image.name = "ghcr.io/cross-rs/x86_64-unknown-freebsd:local"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-gnu"]

[build]
pre-build = ["apt-get update && apt-get install -y --no-install-recommends pkg-config"]

# This target's image was added after the cross 0.2.5 release.
[target.riscv64gc-unknown-linux-musl]
image = "ghcr.io/cross-rs/riscv64gc-unknown-linux-musl:main"
