#[allow(dead_code)]
pub enum TcaCake {
    Unspec = 0,
    Pad = 1,
    BaseRate64 = 2,
    DiffservMode = 3,
    ATM = 4,
    FlowMode = 5,
    Overhead = 6,
    RTT = 7,
    Target = 8,
    Autorate = 9,
    Memory = 10,
    NAT = 11,
    Raw = 12,
    Wash = 13,
    MPU = 14,
    Ingress = 15,
    AckFilter = 16,
    SplitGso = 17,
    FwMark = 18,
    FwMarkStore = 19,
    SCE = 20,
}
