# Copyright 2023 Google LLC
# Licensed under the Apache License, Version 2.0.

name: OSV-Scanner

on:
  pull_request:
    branches: [master, v1]
  schedule:
    - cron: "12 12 * * 1"
  push:
    branches: [master, v1]

permissions: {}

jobs:
  scan-scheduled:
    permissions:
      contents: read
      security-events: write
      actions: read
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.6.0
    with:
      scan-args: ./
  scan-pr:
    permissions:
      contents: read
      security-events: write
      actions: read
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.6.0
    with:
      scan-args: ./
